### ISSUE TITLE
How can i change the batch size?

### ISSUE THREAD

**Issue by Jeiyoon** [ksanjeevan/crnn-audio-classification#11]
Hi 

how can i change the batch size in your code?

thank you 

kindly regards

**Comment by ksanjeevan** [comment]
Hi @Jeiyoon, you can change the batch size in `config.json`, e.g.: https://github.com/ksanjeevan/crnn-audio-classification/blob/f09449b87ed61d28b82931c7055d033a7b69160b/config.json#L9
