### ISSUE TITLE
Need Help as I am beignner in Audio classification

### ISSUE THREAD

**Issue by soumochatterjee** [ksanjeevan/crnn-audio-classification#12]
I am unable to get what I should return for Custom audio data forn CRNN model... 

Like for image dataset class we return image array in numpy and its label through the get_item function in custom dataset class..
Likewise what should I return in Custom dataset class with label of audio for my custom audio dataset.

**Comment by ksanjeevan** [comment]
audio torch datasets can also return a numpy array and a label. The convention used here and in torchaudio is `(channel, signal)`. See here: https://github.com/ksanjeevan/crnn-audio-classification/blob/f09449b87ed61d28b82931c7055d033a7b69160b/data/data_sets.py#L24
