### ISSUE TITLE
How can I customize the model arch crnn.cfg

### ISSUE THREAD

**Issue by takeofuture** [ksanjeevan/crnn-audio-classification#16]
There seem to be possible to modify the number in crnn.cfg
But how do I add more layers in crnn.cfg
I am newbee for this type of implementation
REPEATx2 is predefined keyword in Pytoch or hardcoded variable name in your code?
If I would like to make 10 CNN before LSTM then, how can I modify?
Aldo if I would like to use different input size, where should I change?

```
[convs_module]
    [conv2d]
        out_channels=16
        kernel_size=3
        stride=1
        padding=valid
    [batchnorm2d]
    [elu]
    [maxpool2d]
        kernel_size=3
        stride=3
    [dropout]
        p=0.1

    REPEATx2
        [conv2d]
            out_channels=32
            kernel_size=4
            stride=1
            padding=valid
        [batchnorm2d]
        [elu]
        [maxpool2d]
            kernel_size=4
            stride=4
        [dropout]
            p=0.1
    END

[moddims]
    permute=[2,1,0]
    collapse=[1,2]

[recur_module]
    [lstm]
        hidden_size = 64
        num_layers = 3
        bidirectional=True

[moddims]
    permute=[1]
```

**Comment by ksanjeevan** [comment]
@takeofuture so some of the details of how the cfg file works will be in https://github.com/ksanjeevan/torchparse. Basically, you can do something like:

```

  [conv2d]
      out_channels=16
      kernel_size=3
      stride=1
      padding=valid
  [batchnorm2d]
  [elu]
  [maxpool2d]
      kernel_size=3
      stride=3
  [dropout]
      p=0.1
[conv2d]
      out_channels=16
      kernel_size=3
      stride=1
      padding=valid
  [batchnorm2d]
  [elu]
  [maxpool2d]
      kernel_size=3
      stride=3
  [dropout]
      p=0.1
...
```
And keep adding convolutions. At no point do you have to pre-define a input size as depending on the model you've defined, multiple input dimensions can be valid.


If using `torchparse` is confusing, or you'd rather define your model some other way, you can just write your own in `net/`, or modify https://github.com/ksanjeevan/crnn-audio-classification/blob/f09449b87ed61d28b82931c7055d033a7b69160b/net/model.py#L29 with whatever post processing you want to do after the stft. Hope this helps!
