### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by yeyicheng** [ksanjeevan/crnn-audio-classification#2]
Hello, is there an existing model to use? And can this be run on Jetson Nano? Thank you.

**Comment by shubham2637** [comment]
have you hosted the trained weights somewhere?? could you please send me the link. would be really helpful

**Comment by ksanjeevan** [comment]
Try this one https://drive.google.com/file/d/1USH6s9gRcKYdM6HKW4QAEWL4DYv9rWIw/view?usp=sharing, let me know know if there are any issues.
