### ISSUE TITLE
questions about transforms

### ISSUE THREAD

**Issue by zhaoyun-ai** [ksanjeevan/crnn-audio-classification#20]
Hi, thanks for your excellent work.
I noticed that there is a class called 'class ImageTransforms' in transforms.py
I want to know if this is an image transformation operation on the spectrogram
In other words, I want to know whether the image transformation is applicable to the spectrogram?

**Comment by ksanjeevan** [comment]
Hi @zhaoyun-ai, that's my mistake, this class was for another net/data. 

In general, we have to be careful what type of "image transforms" we apply to spectrograms. For example, doing stretching for an image with linear interpolation might be valid, while it won't be for spectrograms. On the other hand adding gaussian noise will be valid for both.

You can find some valid spectrogram augmentation in [pytorch/audio](https://pytorch.org/audio/stable/transforms.html).

**Comment by zhaoyun-ai** [comment]
Thank you for your reply, I will close this question
