### ISSUE TITLE
About UrbanSound8K

### ISSUE THREAD

**Issue by MichelleYang2017** [ksanjeevan/crnn-audio-classification#6]
About the train dataset urbansound8K, I saw the dataset introduction. In my training, whether use 9 folds to train and the left one fold should to be validate, and repeat this process？The process doesn't have truly test dataset?

**Comment by ksanjeevan** [comment]
Yeah so in the [website](https://urbansounddataset.weebly.com/urbansound8k.html) they explain how they do the cross fold validation. So instead of doing a train/val/test split they do 10-fold cross validation, so you'd test on each fold separately and then combine the results.

**Comment by MichelleYang2017** [comment]
ok，3ks
